version: "3.8"
services:
  # Application
  app:
    container_name: app
    build:
      context: ./docker/services/app
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./src/PharmApp:/var/www
  # Web Server
  web:
    container_name: web
    build:
      context: ./docker/services/web
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./src/PharmApp:/var/www
    ports:
      - "8080:80"
  # Database
  database:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: pharmapp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "33066:3306"
  # Database Management
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=user
      - PMA_PASSWORD=password
      - PMA_PORT=3306
    depends_on:
      - "database"
    ports:
      - "8888:80"
  # Caching
  redis:
    container_name: redis-Caching
    image: redis:alpine
    volumes:
      - ./docker/volumes/redis:/data
    ports:
      - "6379:6379"
  # Mailing Server
  mailhog:
    container_name: mailhog-Mailing
    image: mailhog/mailhog:latest
    logging:
      driver: "none"
    ports:
      - "1025:1025"
      - "8025:8025"